//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fss.HumanCapitalManager.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateSkillLink
    {
        public int AssociateSkillLinkID { get; set; }
        public int AssociateID { get; set; }
        public int SkillID { get; set; }
    }
}
